[project]
name = "arxiv-analysis"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "google-genai>=1.60.0",
    "google-generativeai",
    "pypdf",
    "python-dotenv",
    "requests>=2.32.5",
    "tqdm",
]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true
